@serverUrl = http://localhost:3000

### Call API
GET {{serverUrl}}/

### Ollama API - Ask question
POST http://localhost:3000/api/ollama
Content-Type: application/json

# {
#   "prompt": "What is the capital of France?"
# }

{
  "prompt": "3 most polluted cities in India"
}

### Weather API - Get weather by city
@city = Howrah
GET {{serverUrl}}/weather/{{city}}

### AQI API - Get cities by AQI threshold
@threshold = 100
@isHigher = true
GET {{serverUrl}}/aqi/cities?threshold={{threshold}}&isHigher={{isHigher}}

### Temperature API - Get cities by temperature range
@min = 15
@max = 40
GET {{serverUrl}}/temperature/cities?min={{min}}&max={{max}}